pipeline {
    agent any

    environment {
        PATH = "$PATH:/usr/local/bin"
    }

    stages {
        stage('Java Build') {
            steps {
                dir('hello_world') {
                    // Compile Java code
                    sh 'java Helloworld.java'
                }
            }
        }

        stage('Node.js Build') {
            steps {
                // Install NVM and Node.js
                sh 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash'
                sh 'export NVM_DIR="$HOME/.nvm"'
                sh '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
                sh '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
                sh 'nvm install node'
            }
        }

        stage('Execute Applications') {
            steps {
                dir('hello_world') {
                    // Run Java application
                    sh 'java Helloworld.java'
                }

                dir('hello_world') {
                    // Run Node.js application
                    sh 'node app.js'
                }
            }
        }
    }
}

