pipeline {
    agent any

    stages {
        stage('Java Build') {
            steps {
                dir('hello_world') {
                    // Compile Java code
                    sh 'java Helloworld.java'
                }
            }
        }

        

        stage('Execute Applications') {
            steps {
                dir('hello_world') {
                    // Run Java application
                    sh 'java Helloworld.java'
                }

                dir('hello_world') {
                    // Run Node.js application
                sh 'npm install'
                 sh 'node app.js'
                }
            }
        }
    }
}


