pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                git 'https://github.com/Harshalmane19/my_second_pipeline.git'
                sh 'mvn package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}
